import os
import glob

import streamlit as st

from pathguard.audio_alerts import AudioAlerter
from pathguard.config import DEFAULT_VIDEO_PATH, CorridorParams, RuntimeParams, load_dynamic_prompts
from pathguard.realtime import PipelineRuntime, process_video


st.set_page_config(page_title="PathGuard HUD", layout="wide")
st.title("🛡️ PathGuard — Obstacle Ahead (In-Path) HUD")


def _status_chip(state: str) -> str:
    colors = {
        "CLEAR": "#1f9d55",
        "OBSTACLE AHEAD": "#dd8a00",
        "TRIP RISK": "#cf222e",
    }
    color = colors.get(state, "#6a737d")
    return f"""
    <div style="padding:8px 12px;border-radius:10px;background:{color};color:white;font-weight:700;font-size:22px;text-align:center;">
      {state}
    </div>
    """


def _discover_dino_prompt_files():
    """Auto-discover available DINO prompt files from Cactus Narrator."""
    options = ["None (use default 60-word static list)"]

    # Check session_state first (freshest — from Cactus Narrator this session)
    if st.session_state.get("cactus_dino_prompt_text"):
        label = "✅ From Cactus Narrator (this session)"
        options.insert(0, label)

    # Scan transcripts/ for saved prompt files
    for f in sorted(glob.glob("transcripts/*_dino_prompt.txt")):
        options.append(f)

    return options


with st.sidebar:
    st.header("Input")
    video_path = st.text_input("Video path", value=DEFAULT_VIDEO_PATH)
    display_width = st.slider("Display width (px)", 640, 1400, 920, 20)
    if not os.path.exists(video_path):
        st.warning("Video path not found on this machine. Update path to continue.")

    st.header("Checklist")
    enable_trip_alarm = st.checkbox("Trip Risk alarm", value=True)
    alarm_cooldown = st.slider("Alarm cooldown (sec)", 0.5, 5.0, 1.5, 0.1)

    st.header("Models")
    use_dino = st.checkbox("Use GroundedDINO", value=True)
    use_depth = st.checkbox("Use Depth Anything V2", value=False)
    show_depth_overlay = st.checkbox("Show depth overlay", value=False)
    use_sam2 = st.checkbox("Use SAM2 (optional)", value=False)
    dino_interval = st.slider("DINO interval", 4, 20, 10)
    depth_interval = st.slider("Depth interval", 4, 20, 10)

    st.header("🔗 Dynamic Prompts (Cactus Integration)")
    prompt_options = _discover_dino_prompt_files()
    selected_prompt_source = st.selectbox(
        "DINO prompt source",
        options=prompt_options,
        help="Select prompts generated by the Cactus Narrator, or use the default static list. "
             "Run the Cactus Narrator on a video first to generate dynamic prompts.",
    )

    st.header("Corridor")
    bottom_w = st.slider("Bottom width frac", 0.60, 0.95, 0.90, 0.01)
    top_w = st.slider("Top width frac", 0.15, 0.60, 0.34, 0.01)
    height_f = st.slider("Height frac", 0.35, 0.75, 0.64, 0.01)
    center_x = st.slider("Center X frac", 0.20, 0.80, 0.50, 0.01)

    st.header("Thresholds")
    occ_thresh = st.slider("Occupancy threshold", 0.005, 0.25, 0.015, 0.0025)
    persistence_frames = st.slider("Persistence frames", 2, 10, 2)
    blur_thresh = st.slider("Blur threshold (Laplacian var)", 20.0, 300.0, 20.0, 5.0)
    stop_flag = st.checkbox("Stop", value=False)
    start = st.button("Start")


status_slot = st.empty()
metrics_slot = st.empty()
frame_slot = st.empty()
events_slot = st.empty()

if start:
    # Resolve the selected DINO prompt source
    if selected_prompt_source.startswith("✅ From Cactus"):
        # Use session_state prompts (freshest)
        from integration.dynamic_prompts import parse_dino_prompt_text, merge_prompts
        from pathguard.config import PROMPTS
        dynamic_text = st.session_state.get("cactus_dino_prompt_text", "")
        dynamic = parse_dino_prompt_text(dynamic_text)
        dynamic_prompts = merge_prompts(PROMPTS, dynamic) if dynamic else list(PROMPTS)
        st.sidebar.success(f"🔗 Using {len(dynamic)} scene-specific + {len(PROMPTS)} static prompts from Cactus")
    elif selected_prompt_source.startswith("transcripts/"):
        # Use a saved file
        dynamic_prompts = load_dynamic_prompts(selected_prompt_source)
        st.sidebar.success(f"📁 Loaded {len(dynamic_prompts)} prompts from {selected_prompt_source}")
    else:
        dynamic_prompts = load_dynamic_prompts(None)

    corridor = CorridorParams(
        bottom_width_frac=bottom_w,
        top_width_frac=top_w,
        height_frac=height_f,
        center_x_frac=center_x,
    )
    runtime = RuntimeParams(
        dino_interval=dino_interval,
        depth_interval=depth_interval,
        occ_thresh=occ_thresh,
        persistence_frames=persistence_frames,
        blur_thresh=blur_thresh,
        use_dino=use_dino,
        use_depth=use_depth,
        show_depth_overlay=show_depth_overlay,
        use_sam2=use_sam2,
    )
    # Override prompts with dynamic ones if available
    if dynamic_prompts:
        runtime.prompts = dynamic_prompts
        st.sidebar.success(f"Loaded {len(dynamic_prompts)} dynamic prompts from Cactus")

    cfg = PipelineRuntime(corridor=corridor, runtime=runtime)
    alerter = AudioAlerter(cooldown_sec=alarm_cooldown) if enable_trip_alarm else None
    prev_state = "CLEAR"

    def _stop() -> bool:
        return bool(stop_flag)

    try:
        for out in process_video(video_path, cfg, stop_flag_fn=_stop):
            status_slot.markdown(_status_chip(out["state"]), unsafe_allow_html=True)
            c1, c2, c3, c4 = metrics_slot.columns(4)
            c1.metric("FPS", f"{out['fps']:.1f}")
            c2.metric("Occupancy", f"{out['occupancy_score']:.3f}")
            c3.metric("Relative distance", str(out["last_distance_bucket"]) if out["last_distance_bucket"] else "-")
            c4.metric("Depth", str(out["depth_status"]))
            state = str(out["state"])
            if alerter is not None and state == "TRIP RISK" and prev_state != "TRIP RISK":
                alerter.alert(state)
            prev_state = state
            frame_slot.image(out["frame_rgb"], channels="RGB", width=int(display_width))

            rows = out["events"]
            if rows:
                events_slot.dataframe(rows, use_container_width=True, hide_index=True)
            else:
                events_slot.write("No events yet.")
    except Exception as exc:
        st.error(f"Pipeline error: {exc}")
else:
    st.write("Configure parameters in the sidebar and click Start.")
