"""
Dynamic Prompt Bridge: Cactus Narrator → PathGuard

Reads the dot-separated noun list generated by Cactus's generate_dino_prompt()
and converts it into a clean Python list for PathGuard's GroundedDINO detector.

Workflow:
    1. Cactus Narrator processes video → generates transcript
    2. generate_dino_prompt() extracts nouns → saves to *_dino_prompt.txt
    3. This module reads that file → returns List[str] for PathGuard's RuntimeParams.prompts

Example:
    Input text:  "crane . worker . tractor . safety vest . rebar ."
    Output list: ["crane", "worker", "tractor", "safety vest", "rebar"]
"""

from pathlib import Path
from typing import List, Optional


def parse_dino_prompt_text(text: str) -> List[str]:
    """Parse a dot-separated Cactus DINO prompt string into a list of noun phrases.

    Args:
        text: Dot-separated string like "crane . worker . tractor ."

    Returns:
        Deduplicated list of lowercase noun phrases.
    """
    if not text or not text.strip():
        return []

    # Split on dots, strip whitespace, drop empties
    raw = [tok.strip().lower() for tok in text.split(".")]
    nouns = [tok for tok in raw if tok]

    # Deduplicate while preserving order
    seen = set()
    result = []
    for noun in nouns:
        if noun not in seen:
            seen.add(noun)
            result.append(noun)
    return result


def load_dino_prompt_file(filepath: str) -> List[str]:
    """Read a Cactus *_dino_prompt.txt file and parse its contents.

    Args:
        filepath: Path to a dino_prompt.txt file generated by Cactus Narrator.

    Returns:
        List of noun phrases, or empty list if file doesn't exist / is empty.
    """
    path = Path(filepath)
    if not path.exists() or not path.is_file():
        return []

    text = path.read_text(encoding="utf-8").strip()
    return parse_dino_prompt_text(text)


def merge_prompts(
    static: List[str],
    dynamic: List[str],
    max_prompts: int = 50,
) -> List[str]:
    """Merge static (default) and dynamic (Cactus-generated) prompt lists.

    Dynamic prompts are prepended (higher priority for scene-specific labels),
    followed by static prompts not already in the dynamic set.
    Capped at max_prompts to avoid GroundedDINO tokenizer overflow.

    Args:
        static:  Default PathGuard prompts from config.PROMPTS.
        dynamic: Cactus-generated prompts from a DINO prompt file.
        max_prompts: Maximum number of prompts (default 50).

    Returns:
        Merged, deduplicated list with dynamic prompts first, capped.
    """
    if not dynamic:
        return list(static)[:max_prompts]

    seen = set()
    result = []

    # Dynamic first (scene-specific, higher priority)
    for prompt in dynamic:
        if len(result) >= max_prompts:
            break
        key = prompt.lower().strip()
        if key and key not in seen:
            seen.add(key)
            result.append(prompt)

    # Static second (fill in anything the dynamic list missed)
    for prompt in static:
        if len(result) >= max_prompts:
            break
        key = prompt.lower().strip()
        if key and key not in seen:
            seen.add(key)
            result.append(prompt)

    return result
