"""
Enriched Telemetry Bridge: PathGuard → Cactus RCP Telemetry

Takes PathGuard's spatial safety data (corridor occupancy, depth buckets,
trip risk flags, event log) and enriches the Cactus-generated RCP telemetry
JSON with spatially-grounded hazard information.

This makes the RCP telemetry more than just semantic — it now includes
actual spatial measurements from the corridor analysis.
"""

import copy
from typing import Any, Dict, List, Optional


def enrich_rcp_with_spatial_data(
    rcp_json: Dict[str, Any],
    pathguard_events: List[Dict[str, Any]],
    final_occupancy: Optional[float] = None,
    final_depth_bucket: Optional[str] = None,
) -> Dict[str, Any]:
    """Inject PathGuard spatial data into an existing RCP telemetry JSON.

    Args:
        rcp_json: The RCP telemetry dict generated by Cactus's generate_rcp_telemetry().
        pathguard_events: List of event dicts from EventStateMachine.events_as_rows().
                         Each has: timestamp_s, state, occupancy_score.
        final_occupancy: Latest corridor occupancy score (0.0 - 1.0).
        final_depth_bucket: Latest depth bucket ("NEAR", "MID", "FAR", or None).

    Returns:
        A new dict with PathGuard spatial data injected under "pathguard_spatial".
    """
    enriched = copy.deepcopy(rcp_json)

    # Add a top-level spatial analysis section
    spatial_summary = {
        "source": "pathguard_corridor_analysis",
        "total_hazard_events": 0,
        "trip_risk_events": 0,
        "obstacle_events": 0,
        "peak_occupancy": 0.0,
        "last_depth_bucket": final_depth_bucket,
        "last_occupancy": final_occupancy,
        "event_log": [],
    }

    for event in pathguard_events:
        state = event.get("state", "")
        occ = event.get("occupancy_score", 0.0)
        ts = event.get("timestamp_s", 0.0)

        spatial_summary["total_hazard_events"] += 1
        spatial_summary["peak_occupancy"] = max(spatial_summary["peak_occupancy"], occ)

        if state == "TRIP RISK":
            spatial_summary["trip_risk_events"] += 1
        elif state == "OBSTACLE AHEAD":
            spatial_summary["obstacle_events"] += 1

        spatial_summary["event_log"].append({
            "timestamp_s": round(ts, 2),
            "state": state,
            "corridor_occupancy": round(occ, 4),
        })

    enriched["pathguard_spatial"] = spatial_summary

    # Also try to enrich individual observations if timestamps overlap
    observations = enriched.get("observations", [])
    if observations and pathguard_events:
        _cross_reference_timestamps(observations, pathguard_events)

    return enriched


def _cross_reference_timestamps(
    observations: List[Dict[str, Any]],
    events: List[Dict[str, Any]],
) -> None:
    """Cross-reference RCP observation timestamps with PathGuard events.

    Mutates observations in-place to add spatial annotations where
    timestamps approximately match.
    """
    for obs in observations:
        ts_str = obs.get("timestamp", "")
        if not ts_str:
            continue

        # Parse MM:SS to seconds
        try:
            parts = ts_str.split(":")
            obs_sec = int(parts[0]) * 60 + int(parts[1])
        except (ValueError, IndexError):
            continue

        # Find the closest PathGuard event within 5 seconds
        closest_event = None
        closest_dist = float("inf")
        for event in events:
            dist = abs(event.get("timestamp_s", 0) - obs_sec)
            if dist < closest_dist:
                closest_dist = dist
                closest_event = event

        if closest_event and closest_dist <= 5.0:
            obs["pathguard_state"] = closest_event.get("state", "UNKNOWN")
            obs["pathguard_corridor_occupancy"] = closest_event.get("occupancy_score", 0.0)

            # Upgrade risk level if PathGuard detected a trip risk
            if closest_event.get("state") == "TRIP RISK":
                obs["risk_level"] = "high"
                existing_hazards = obs.get("hazards", [])
                if "trip_hazard_in_corridor" not in existing_hazards:
                    existing_hazards.append("trip_hazard_in_corridor")
                    obs["hazards"] = existing_hazards
